ForexMasters-site/Controllers/MasterclassController.cs
using ForexMasters_site.Models.Data;
using ForexMasters_site.Models.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ForexMasters_site.Controllers
{
    [Authorize]
    public class MasterclassController : Controller
    {
        private IRepositoryWrapper _repository;
        private UserManager<IdentityUser> _userManager;
        public MasterclassController(IRepositoryWrapper repository, UserManager<IdentityUser> userManager)
        {
            _repository = repository;
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);

            User ActiveUser = _repository.User.FindAll()
                                              .Where(u => u.Email == user.Email)
                                              .FirstOrDefault();
            return View(ActiveUser);
        }

        public IActionResult ViewFlashcards()
        {
            var Flashcards = _repository.Flashcard.FindAll();
            return View(Flashcards);
        }

        public IActionResult Courses()
        {
            var Categories = _repository.Category.FindAll();
            return View(Categories);
        }

        public IActionResult Topics(int id)
        {
            var topics = _repository.Topic.FindAll().Where(t => t.CategoryID == id).OrderBy(t => t.Name);
            if (User.IsInRole("Admin"))
                return View(topics);
            else
            {
                bool approved = _repository.User.FindByCondition(u => u.Name == User.Identity.Name)
                                            .FirstOrDefault()
                                            .isActive;

                if (approved)
                    return View(topics);
                else
                    return Redirect("/Masterclass/AccessDenied");
            }
        }
        public IActionResult PDFs()
        {
            var documents = _repository.Document.FindAll().Where(d => d.TopicID == null).OrderBy(d => d.Name);
            if (User.IsInRole("Admin"))
                return View(documents);
            else
            {
                bool approved = _repository.User.FindByCondition(u => u.Name == User.Identity.Name)
                                            .FirstOrDefault()
                                            .isActive;

                if (approved)
                    return View(documents);
                else
                    return Redirect("/Masterclass/AccessDenied");
            }
        }
        public IActionResult EnterPassword(string id)
        {
            Topic topic = _repository.Topic.FindByCondition(t => t.TopicID == id).FirstOrDefault();
            return View(topic);
        }
        [HttpPost]
        public IActionResult EnterPassword(string id, string password)
        {
            Topic topic = _repository.Topic.FindByCondition(t => t.TopicID == id).FirstOrDefault();
            
            if (password.CompareTo(topic.Password) == 0)
                return RedirectToAction("TopicDetail", topic);
            else
            {
                ViewBag.Message = "failed";
                return View(topic);
            }


        }
        public IActionResult TopicDetail(Topic topic)
        {
            ViewBag.Videos = _repository.Video.FindByCondition(v => v.TopicID == topic.TopicID);
            ViewBag.Documents = _repository.Document.FindByCondition(d => d.TopicID == topic.TopicID);
            return View(topic);
        }
        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

ForexMasters-site/Controllers/RoleAdminController.cs
using ForexMasters_site.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ForexMasters_site.Controllers
{
    public class RoleAdminController : Controller
    {
        private RoleManager<IdentityRole> _roleManager;
        private UserManager<IdentityUser> _userManager;

        public RoleAdminController(RoleManager<IdentityRole> roleManager, UserManager<IdentityUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        public ViewResult Index()
        {
            return View(_roleManager.Roles);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Required]string name)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result
                    = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    AddErrorsFromResult(result);
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    AddErrorsFromResult(result);
                }
            }
            else
            {
                ModelState.AddModelError("", "No role found");
            }
            return View("Index", _roleManager.Roles);
        }

        public async Task<IActionResult> Edit(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            List<IdentityUser> members = new List<IdentityUser>();
            List<IdentityUser> nonMembers = new List<IdentityUser>();
            foreach (IdentityUser user in _userManager.Users)
            {
                var list = await _userManager.IsInRoleAsync(user, role.Name)
                                ? members : nonMembers;
                list.Add(user);
            }
            return View(new RoleEditModel
            {
                Role = role,
                Members = members,
                NonMembers = nonMembers
            });
        }

        [HttpPost]
        public async Task<IActionResult> Edit(RoleModificationModel model)
        {
            IdentityResult result;
            if (ModelState.IsValid)
            {
                foreach (string userId in model.IdsToAdd ?? new string[] { })
                {
                    IdentityUser user = await _userManager.FindByIdAsync(userId);
                    if (user != null)
                    {
                        result = await _userManager.AddToRoleAsync(user, model.RoleName);
                        if (!result.Succeeded)
                        {
                            AddErrorsFromResult(result);
                        }
                    }
                }
                foreach (string userId in model.IdsToDelete ?? new string[] { })
                {
                    IdentityUser user = await _userManager.FindByIdAsync(userId);
                    if (user != null)
                    {
                        result = await _userManager.RemoveFromRoleAsync(user, model.RoleName);
                        if (!result.Succeeded)
                        {
                            AddErrorsFromResult(result);
                        }
                    }
                }
            }
            if (ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return await Edit(model.RoleId);
            }
        }

        private void AddErrorsFromResult(IdentityResult result)
        {
            foreach (IdentityError error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
        }
    }
}

ForexMasters-site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Forex Masters</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link asp-href-include="lib/font-awesome/css/all.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
            <div class="container">
                <!--Navbar Brand-->
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <h3 class="text-light">
                        <img src="~/images/logos/ForexMasters_Logo.png" width="100" />
                    </h3>
                </a>
                <!--Hamburger menu-->
                <button class="navbar-toggler btn-outline-warning" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <!--Nav Items-->
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Signals">Signals</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Resources">Resources</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Contact">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Disclaimer">Disclaimer</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-link font-weight-bold">Hello,@User.Identity.Name</li>
                            @if (!User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Masterclass" asp-action="Index">Masterclass</a>
                                </li>
                            }
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Tools</a>
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item" asp-controller="Admin" asp-action="Index">User Management</a>
                                        <a class="dropdown-item" asp-controller="RoleAdmin" asp-action="Index">Role Management</a>
                                    </div>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Content Management</a>
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item" asp-controller="Admin" asp-action="CreateCategory">Add Category</a>
                                        <a class="dropdown-item" asp-controller="Admin" asp-action="DeleteCourse">Delete Category</a>
                                        <a class="dropdown-item" asp-controller="Admin" asp-action="CreateTopic">Add Topic</a>
                                        <a class="dropdown-item" asp-controller="Admin" asp-action="TopicsPasswords">Modify Topics</a>
                                        <a class="dropdown-item" asp-controller="Admin" asp-action="CreateFlashcard">Add Flashcard</a>
                                        <a class="dropdown-item" asp-controller="Admin" asp-action="CreatePDF">Add PDFs</a>
                                    </div>
                                </li>
                            }
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Content</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="Masterclass" asp-action="ViewFlashcards">Flashcards</a>
                                    <a class="dropdown-item" asp-controller="Masterclass" asp-action="Courses">Courses</a>
                                    <a class="dropdown-item" asp-controller="Masterclass" asp-action="PDFs">PDFs</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <form asp-controller="Account" asp-action="Logout" method="post">
                                    <button class="btn btn-link nav-link" type="submit">Logout</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link font-weight-bold" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        @*<partial name="_CookieConsentPartial" />*@
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer style="background-color: black;" class="mt-4">
        <!-- Footer Links -->
        <div class="container text-light text-center text-md-left pt-5">
            <!-- Grid row -->
            <div class="row">
                <div class="contact col-sm-12 col-md-4 mx-auto mb-4">
                    <hr class="bg-light" />
                    <h6><i class="fa fa-envelope" aria-hidden="true"></i> Email us on:</h6>
                    <p>
                        <a href="mailto:support@forexmasters-fx.com" class="text-white">support@forexmasters-fx.com</a>
                        <br />
                        <a href="mailto:info@forexmasters-fx.com" class="text-white">info@forexmasters-fx.com</a>
                    </p>
                </div>
                <br />
                <div class="contact col-sm-12 col-md-4 mx-auto mb-4">
                    <hr class="bg-light" />
                    <h6><i class="fa fa-phone-alt" aria-hidden="true"></i> Call/WhatsApp:</h6>
                    <p>
                        +263 71 761 9529<br />
                        +27 76 044 30 89
                    </p>
                </div>
                <br />
                <div class="contact col-sm-12 col-md-4 mx-auto mb-4">
                    <hr class="bg-light" />
                    <h6><i class="fa fa-map-marker" aria-hidden="true"></i> Location:</h6>
                    <p>
                        Harare, Zimbabwe<br />
                        Bloemfontein, South Africa
                    </p>
                </div>
            </div>
            <!-- //Grid row -->
            <!-- Footer Links -->
            <!-- Copyright -->
            <div class="text-center text-muted">
                &copy; Copyright @DateTime.Now.Year.ToString() Forex Masters. All rights reserved
                <br />
                Developed by <a class="text-muted" href="http://katlegomokhethi.com/">Katlego Mokhethi</a>
            </div>
        </div>
        <!-- Copyright -->
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>